// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sonofbytes/gocrawl/retriever/server (interfaces: StoreService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockStoreService is a mock of StoreService interface
type MockStoreService struct {
	ctrl     *gomock.Controller
	recorder *MockStoreServiceMockRecorder
}

// MockStoreServiceMockRecorder is the mock recorder for MockStoreService
type MockStoreServiceMockRecorder struct {
	mock *MockStoreService
}

// NewMockStoreService creates a new mock instance
func NewMockStoreService(ctrl *gomock.Controller) *MockStoreService {
	mock := &MockStoreService{ctrl: ctrl}
	mock.recorder = &MockStoreServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStoreService) EXPECT() *MockStoreServiceMockRecorder {
	return m.recorder
}

// SetConnection mocks base method
func (m *MockStoreService) SetConnection(arg0 string) error {
	ret := m.ctrl.Call(m, "SetConnection", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetConnection indicates an expected call of SetConnection
func (mr *MockStoreServiceMockRecorder) SetConnection(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConnection", reflect.TypeOf((*MockStoreService)(nil).SetConnection), arg0)
}

// Submit mocks base method
func (m *MockStoreService) Submit(arg0 context.Context, arg1, arg2 string, arg3 []string) error {
	ret := m.ctrl.Call(m, "Submit", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Submit indicates an expected call of Submit
func (mr *MockStoreServiceMockRecorder) Submit(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockStoreService)(nil).Submit), arg0, arg1, arg2, arg3)
}
